env = OMARCHY_SCREENSHOT_DIR,$HOME/Pictures/Screenshots
env = OMARCHY_SCREENRECORD_DIR,$HOME/Videos/ScreenRecordings

exec-once = radiotray-ng
exec-once = torrent-sentry

#### NAVIGATION & SHORTCUTS
$CMD = Alt

# Walker launcher and omarchy menu
unbind = SUPER, SPACE
unbind = SUPER ALT, SPACE

bindd = $CMD, Space, Launcher, exec, omarchy-launch-walker
bindd = SUPER,SPACE, Omarchy Menu, exec, omarchy-menu

# Workspace navigation
bind = $CMD, A, workspace, 1
bind = $CMD, S, workspace, 2
bind = $CMD, D, workspace, 3

bind = $CMD SHIFT, A, movetoworkspacesilent, 1
bind = $CMD SHIFT, S, movetoworkspacesilent, 2
bind = $CMD SHIFT, D, movetoworkspacesilent, 3

bind = $CMD, 1, exec, omarchy-launch-or-focus "Brave-browser" "brave"
bind = $CMD, 2, exec, omarchy-launch-or-focus "Alacritty" "alacritty"
bind = $CMD, 3, exec, omarchy-launch-or-focus "Ferdium" "ferdium"
bind = $CMD, 4, exec, omarchy-launch-or-focus "Notion" "notion-app"

# Shortcuts
bind = $CMD, Q, killactive,
bind = $CMD, F, togglefloating,

# Cycle through applications on active workspace
bind = $CMD,       Tab, cyclenext
bind = $CMD SHIFT, Tab, cyclenext, prev

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# toggle radiotray-ng stream
bindl = SHIFT, XF86AudioPause, exec, dbus-send --session --type=method_call --dest=com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.stop
bindl = SHIFT, XF86AudioPlay, exec, dbus-send --session --type=method_call --dest=com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.play

#### LOOK AND FEEL

general { 
    gaps_in = 2
    gaps_out = 8
    border_size = 1
    resize_on_border = true
}

decoration {
    rounding = 4
    # active_opacity = 1.0
    # inactive_opacity = 0.7
    fullscreen_opacity = 1
    
    blur {
        enabled = true
        size = 2
        passes = 3
        special = true
        brightness = 0.70
        contrast = 0.85
        # new_optimizations = true
        # ignore_opacity = true
        # xray = false
        # popups = true
        # vibrancy=0.1696
        # brightness = 0.5 
        # contrast = 0.9
    }
}

# waybar blur
layerrule = blur on, ignore_alpha 0.1, match:namespace waybar
layerrule = blur on, ignore_alpha 0.1, match:namespace walker
layerrule = blur on, ignore_alpha 0.1, match:namespace notifications



